apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-daffy-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-daffy-frontend
  template:
    metadata:
      labels:
        app: ai-daffy-frontend
    spec:
      containers:
        - name: ai-daffy-frontend
          image: randomlettergenerator/ai-daffy-frontend:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "2000m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-daffy-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-daffy-backend
  template:
    metadata:
      labels:
        app: ai-daffy-backend
    spec:
      containers:
        - name: ai-daffy-backend
          image: randomlettergenerator/ai-daffy-backend:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "2000m"
          ports:
            - containerPort: 3000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ai-daffy-frontend-service
spec:
  type: NodePort
  selector:
    app: ai-daffy-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
---
apiVersion: v1
kind: Service
metadata:
  name: ai-daffy-backend-service
spec:
  selector:
    app: ai-daffy-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ai-daffy-frontend-istio-service
  namespace: default
  labels:
    istio-prometheus-scrape: "true"
spec:
  selector:
    app: ai-daffy-frontend
  ports:
    - name: http-envoy-prom
      port: 15020
      targetPort: 15020
---
apiVersion: v1
kind: Service
metadata:
  name: ai-daffy-backend-istio-service
  namespace: default
  labels:
    istio-prometheus-scrape: "true"
spec:
  selector:
    app: ai-daffy-backend
  ports:
    - name: http-envoy-prom
      port: 15020
      targetPort: 15020
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-to-backend
spec:
  podSelector:
    matchLabels:
      app: ai-daffy-backend
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: ai-daffy-frontend
      ports:
        - protocol: TCP
          port: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        # Serve static files
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        # Proxy API requests to backend
        location /api/ {
            proxy_pass http://ai-daffy-backend-service:3000;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Error handling
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-service-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: istiod
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - interval: 10s
      path: /metrics
      port: http-monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-sidecar-servicemonitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      istio-prometheus-scrape: "true"
  namespaceSelector:
    any: true
  endpoints:
    - port: http-envoy-prom
      path: /metrics
      interval: 10s
      scheme: http
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: fake-traffic-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fake-traffic-virtualservice
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - fake-traffic-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: ai-daffy-frontend-service
            port:
              number: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
type: Opaque
data:
  OPENAI_API_KEY: c2stcHJvai0xSGxBNU1QVUtybWUxbmdsQlJSUkM4YmI3NGhoejFfMGlJQnFWSksyT0R4S1VtMlZRLW10d3NMMEVOTlptbWtoLVBCU2JkM042LVQzQmxia0ZKLXlHWWk2TXFjak0xaGFnSHJoTHV2czg1U0JUX2puOFN0OHhPeXJJSFFVcXZOV2w3a3FoN2RLUmJKcHNJQlVfU2M0ODlHeHptUUE=
---

